### ISSUE TITLE
Created .pkpass can be unzip but unable to open in iphone or mac

### ISSUE THREAD

**Issue by onlyamir007** [drallgood/jpasskit#101]
I can create .pkpass but im unable to open open in mac or iphone.
do i have to define "'Content-type: application/vnd.apple.pkpass')" some where ?

**Comment by drallgood** [comment]
Hey @onlyamir007 
Somehow I missed this one.

Have you checked the created pass using the signposts tool Apple provides? Or looked at the log of the devices to see whether there are any errors related to this?

Common issues are:
- Certificates are invalid or have expired
- Invalid content (even though jPasskit does its best to prevent this from happening)

**Comment by drallgood** [comment]
No response. Closing issue

**Comment by szebedy** [comment]
Had the same issue, the problem was that the pkpass file was not valid (certificate attributes and pass.json did not match).

You can validate your generated pkpass file here and find out what is wrong with it: http://pkpassvalidator.com/

The solution is to generate a valid pkpass file, that passes all the tests of the validator.
