### ISSUE TITLE
Separate validation and data model

### ISSUE THREAD

**Issue by drallgood** [drallgood/jpasskit#140]
As per a previous discussion with @stepio I think we should separate the validation functionality from the data model classes.

Looking for ideas how to best solve this.

Ideas:

- Register validators per model class
- Create a validation utility that allows you to register those validators and then uses them to validate all or parts of the pass tree

**Comment by JocoNagy** [comment]
Hi,

I really like this enhancement :)
I also have some ideas 

- The first thing that came into my mind was visitor pattern i think it could be also an option for separating validation.

- Another thing that I thought of is to provide builders for these model objects and they could handle the validation. With this it is easy to turn the data objects immutable, which is always a good thing and that would also give a nicer fluent way to construct them. I also realised that the PKPass object is really huge and it is not so convenient to use because you have to set a lot of fields on a single object. This makes it hard to write nice looking and easy to test classes that create a PKPass. Decomposing it would help a lot with this and it might simplify validation as well.

**Comment by drallgood** [comment]
I thought about the builder pattern as well @Joco-Nagy 
To me that's the most appropriate. But then again I'm open for other suggestions.

Regarding the class sizes:
The classes are directly modeled after Apple's APIs which makes conversion to and from JSON easier.
However, removing the validation logic should actually significantly decrease the size and complexity.

**Comment by stepio** [comment]
I agree with @drallgood - if no other volunteers, I can try implementing this via PR.

**Comment by stepio** [comment]
What about switching to Java 8?

**Comment by drallgood** [comment]
> What about switching to Java 8?

I actually did that in the past but then people wanted to use it in previous versions so I decided to roll it back. Maybe now is the time to finally do it!
