### ISSUE TITLE
Cannot add pass to wallet from IOS (only in latest version)

### ISSUE THREAD

**Issue by BESAFX** [drallgood/jpasskit#196]
Hi @drallgood 
After upgrading to latest version 0.2.0-SNAPSHOT, another issue occurs after creating pass and trying to send it to IOS wallet app through SMS, a message reported to me that IOS cannot download the file, despite pass downloaded with no errors in case of using Android OS or Chrome.

So what you think, is that related to latest version used ?

**Comment by drallgood** [comment]
It may be.

First step would be to look at the device logs and/or confirm the pass is valid using the signpass tool Apple provides

**Comment by drallgood** [comment]
Probably closed by #217

**Comment by szebedy** [comment]
Had the same issue, the problem was that the pkpass file was not valid (certificate attributes and pass.json did not match).

You can validate your generated pkpass file here and find out what is wrong with it: http://pkpassvalidator.com/

The solution is to generate a valid pkpass file, that passes all the tests of the validator.
