### ISSUE TITLE
can't add to passbook????????

### ISSUE THREAD

**Issue by xiaoyangh** [drallgood/jpasskit#2]
```
   it can't add to passbook.
```

This great code，but creat the pkpass  error: The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.However i use the openssl creat the pkpass can add to passbook. when i use the jpasskit it can't add to passbook.

who can help me?
xiaoyangh@foxmail.com

**Comment by ahujber** [comment]
@topgun  Thanks for sharing your experience, I've had the same problem. I did lots of research why my pass not working on IOS, when I found your comment.

@drallgood  Maybe you can add this little detail to your tutorial, because I haven't find any information about this, that without icon the pass won't work.

**Comment by juminoz** [comment]
I'm running into an issue where if I use the same pass.cer to sign the pass using the signpass app from Apple, it works fine and I'm able to open it up on my iPhone X and also the simulator. However, when I do it through jpasskit, I'm getting the same error mentioned above. The original private key was generated on a different laptop, but since I could sign using the signpass app, I didn't think it matters. Any idea on why this would happen?

Error evaluating trust. Status: 0 ResultType: 0 Description:  [leaf AnchorApple ChainLength IntermediateMarkerOid MissingIntermediate] - "Pass Type ID: pass.com.xyretail.pop" certificates do not meet pinning requirements.
cert[0]: IntermediateMarkerOid =(path)[force]> 0
Signature validation: *** FAILED ***
Invalid data error reading pass pass.com.xyretail.pop/3eb3a26d-ace6-41fd-b836-80c9228d2428. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.
error	10:52:08.173882-0400	Passbook	Failed to add pass: 'file:///Users/aaa/Downloads/415d8add-cb17-495f-a5e4-c2e03c64d24d.pkpass' Error Domain=PKPassKitErrorDomain Code=1 "The pass cannot be read because it isn’t valid." UserInfo={NSLocalizedDescription=The pass cannot be read because it isn’t valid., NSUnderlyingError=0x600000e53600 {Error Domain=PKPassKitErrorDomain Code=1 "The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified." UserInfo={NSLocalizedDescription=The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.}}}.

**Comment by drallgood** [comment]
Sounds like you have an issue with your certificate or chain. Make sure you're using the correct files there 

The mac unfortunately doesn't do a proper validation and it also uses the local trust store. So yes that might be why

**Comment by allanalves** [comment]
@juminoz Did you manage to find a workaround for that?

**Comment by juminoz** [comment]
> @juminoz Did you manage to find a workaround for that?

Yes, don't use Apple certificate for 2030. Use the 2023 one. That was the issue.

**Comment by allanalves** [comment]
> > @juminoz Did you manage to find a workaround for that?
> 
> Yes, don't use Apple certificate for 2030. Use the 2023 one. That was the issue.

@juminoz  Oh thanks for that. It worked!

**Comment by AlexLybbert** [comment]
@juminoz You beautiful person!!! I have been struggling with this for almost 3 weeks now! DON'T US THE 2030 ONE!!!!!

**Comment by drallgood** [comment]
And here's finally the explanation from Apple:

https://developer.apple.com/support/wwdr-intermediate-certificate/

Summary: keep the old certificate around until further notice
