### ISSUE TITLE
Can't open the generated PKPASS file

### ISSUE THREAD

**Issue by nwprojectsc** [drallgood/jpasskit#204]
Hi,
I've been working on an implementation that wishes to leverage jpasskit to generate a wallet pass. I originally tried generating PKPASS file on windows using the necessary certificates, while I was able to successfully generate the PKPASS file on my windows machine, the pass file couldn't be opened on any iOS device. So I even tried running the code on my colleagues iOS machine and it ends the same way where I am able generate the pass file but not able to open it on any iOS device. Is there any fix to this?

**Comment by fabio-percivaldi** [comment]
Having the same problem here, when generating the passkit the signature seems to be corrupted and this prevent the file to be opened correctly.

**Comment by drallgood** [comment]
@fabio-percivaldi @nwprojectsc 
Have you checked the device logs to see the error message?
Have you used the signposts util to confirm the signature?

Both tools are really helpful resources

**Comment by drallgood** [comment]
Probably closed by #217

**Comment by szebedy** [comment]
Had the same issue, the problem was that the pkpass file was not valid (certificate attributes and pass.json did not match).

You can validate your generated pkpass file here and find out what is wrong with it: http://pkpassvalidator.com/

The solution is to generate a valid pkpass file, that passes all the tests of the validator.
