### ISSUE TITLE
PKSigningUtil is deprecated warning

### ISSUE THREAD

**Issue by kinju4374** [drallgood/jpasskit#371]
Hi,

As you have mentioned in tutorial, I have created the main class and a .pkPass file was generated but it is not working in both email and mac.

So, I thought might be not signed properly and PKSigningUtil is showing deprecated warning as below

![image](https://user-images.githubusercontent.com/17248153/144830707-af2f5164-5f71-41df-9eb6-25fbc1aec116.png)

Could you please let me know what needs to be changed for signing the pass?

Also, is it possible to generate and store pass.json?

**Comment by drallgood** [comment]
@kinju4374 
I think our tutorials need updating. Sorry about that

Please use one of the implementations in 'jpasskit/src/main/java/de/brendamour/jpasskit/signing'

**Comment by kinju4374** [comment]
@drallgood Yes, I was able to find the solution and could resolve the problems. Now, I am not able to understand 2 things, could you please help me?

1) from where the logo is set? What do I need to do if I want to change the logos? Is there any builder available for it same as locationBuilder, barcodeBuilder, etc?
2) I was able to generate my initial passbook file and was able to check with my iOS developer, the only issue we had was that the file size is 1.6 MB and due to this, it's not opening in the mobile app? Any suggestions?

Thanks

**Comment by kinju4374** [comment]
Hi @drallgood ,

I was able to solve the first point I think by adding the **AppleWWDRCA.cer** file from issue #231 but a quick question why that file is needed?


I added a pass.cer file which my developer sent but in that case it worked only for him.

**Comment by drallgood** [comment]
@kinju4374 Glad you could solve some of those issues yourself :) 

For point 3: I don't think the size is an issue. Frequently the issue is an issue with the signature (wrong certificates) or mismatch in certificate and teamIdentifier. The device's console should tell you what's going on.
You can, however, reduce the size of the assets used. That might help.

For point 4:
jPasskit.server is only a reference implementation, not a fully working solution. You can integrate it into your own solution. Or use it as reference to roll your own.

**Comment by kinju4374** [comment]
Thanks, @drallgood for the response.

I need to ask one more question, I am trying to export it in the form of a jar file to use it in Oracle instance but the problem I am facing is that it's not including all the maven dependencies jar in the final jar.

Is there a way to achieve this?
