### ISSUE TITLE
iPhone is not recognizing .pkpass

### ISSUE THREAD

**Issue by krbhaskar4u** [drallgood/jpasskit#43]
Hi 
I am generating .pkpass using below code, but it has not been recognized by iPhone. When I am sending email to my iPhone and attaching .pkpass as attachment, the attached .pkpass file showing null. 
Please guide me. 

Regards,
Kumar

**Comment by jaimoto81** [comment]
1. Do you have the right certificates?  Which it´s the output of the log on the device

2. I´ve had an issue with files attached from the outlook client, it seems that the mail client unzipped and zipped again the file (pkpass) in order to scan the elements inside. So, that operation corrupted the data of the pkpass file. We tried with other client (web client) and it worked

**Comment by drallgood** [comment]
You can also check the console of your device by connecting it to your Mac and using xCode to access it.
The console should give you some indication as for what is wrong. Finally, you can always send me a sample and I could take a quick glance on it
