### ISSUE TITLE
Push Notification and Change Message

### ISSUE THREAD

**Issue by vineetravi107** [drallgood/jpasskit#95]
1. I was trying to send push notification to update Apple Store pass using pushToken which I receive once the device is registered. I receive two tokens, one is pktoken and other is jsontoken.. Which One do I need to use to send push notification. 

2. Using either, I don't receive any notification on iPhone. As you mentioned to use payload as empty `{}` but I do find people using `{"aps":""}`. Which one will work here?

3. Also, I have an Auxiliary field (Points) in my pass where Key (points), label (Points) and value (1024) are set and the points need to update on push notification. I saw a method named `setChangeMessage` and following is the code I use:

   `pkField.setKey("points");`
   `pkField.setValue("fetchingLatestPointsFromTableInStringFormat");` 
    `//Dynamic Value Eg:    pkField.setValue("1024");`

   `pkField.setLabel("Points");`
   `pkField.setChangeMessage("Points Changed : %@");`

   So suppose I want to increase the points to 2048 in my table and send a push notification, will I    receive  notification on my phone with alert and changed points, using the code above? Or do I have to write something as below:

   `pkField.setKey("points");`
   `pkField.setValue("fetchingOldPointsFromTableInStringFormat");`
   `pkField.setLabel("Points");`
   `pkField.setChangeMessage("fetchingNewPointsFromTableInStringFormat");`

**Comment by drallgood** [comment]
@vineetravi107 
1) you mean the PKPushToken? That's just a class representing the JSONToken you get from Apple.

2) Have you see this: https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/apns/PKSendPushNotificationUtil.java


That should take care of almost everything you need

3) The first one. Keep in mind that you might want to add a translation key instead of a message and include a strings file in your pass. This way you will be able to support multiple languages at the same time
